name: demo
on:
  [push]

jobs:
  run:
    name: Sync GitHub to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Single repo mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/OxalisCu
          dst: gitee/OxalisCu
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          white_list: "EasyCharts-forum-front"
          force_update: true